name: CI
on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  pnpm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 14, 16]
      fail-fast: false

    name: "Build&Test: node-${{ matrix.node_version }}, ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4

  build:
    - name: deploy
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
        vercel-args: "--prod" #Optional
        vercel-org-id: ${{ secrets.ORG_ID}} #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
